In [8]:
#1. Greedy Policy
def clip(x):
    return min(3, max(0, x))

def Greedy_Policy(epoch):
    G = [[-0.0]*4 for _ in range(4)]
    def update():
        G_memory = [[-0.0]*4 for _ in range(4)]
        for i in range(4):
            for j in range(4):
                if i==j and (i==0 or i==3):
                    continue

                summation = []

                for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]:
                    i2 = clip(i2)
                    j2 = clip(j2)
                    summation.append(G[i2][j2]/4)

                G_memory[i][j] = -1 + sum(summation)

        return G_memory


    for i in range(epoch):
        G = update()

    print(f"\nGreedy_Policy {epoch} times iteration")
    for line in G:
        print(list(map(lambda x: round(x, 1), line)))

def Value_Iteration(epoch):
    G = [[-0.0]*4 for _ in range(4)]
    def update():
        G_memory = [[-0.0]*4 for _ in range(4)]
        for i in range(4):
            for j in range(4):
                if i==j==0 or i==j==3:
                    continue

                summation = []

                for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]:
                    i2, j2 = clip(i2), clip(j2)
                    j2 = clip(j2)
                    summation.append(G[i2][j2])

                G_memory[i][j] = -1 + max(summation)

        return G_memory


    for i in range(epoch):
        G = update()

    print(f"\nValue_Iteration {epoch} times iteration")
    for line in G:
        print(list(map(lambda x: round(x, 1), line)))

if __name__ == '__main__':
    epoch = 100
    Greedy_Policy(epoch=epoch)
    Value_Iteration(epoch=epoch)


Greedy_Policy 100 times iteration
[-0.0, -13.9, -19.9, -21.9]
[-13.9, -17.9, -19.9, -19.9]
[-19.9, -19.9, -17.9, -13.9]
[-21.9, -19.9, -13.9, -0.0]

Value_Iteration 100 times iteration
[-0.0, -1.0, -2.0, -3.0]
[-1.0, -2.0, -3.0, -2.0]
[-2.0, -3.0, -2.0, -1.0]
[-3.0, -2.0, -1.0, -0.0]


In [14]:
#1. Greedy Policy
import numpy as np

global grid_height

global grid_width
grid_height =4
grid_width = 4

def Policy(epoch):
    value_table = np.zeros([grid_height, grid_width], dtype=float) ## value table declaration
    for tmp in range(epoch):
        for tmp in range(grid_width):
            update_table = np.zeros([grid_height, grid_width], dtype=float) ## update table declaration

        for j in range(grid_width):
            for i in range(grid_height):
                if i==j and (i==0 or i==3):
                    continue

                tmp = []

                for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]: # South East North West move pair
                    i2 = min(3, max(0, i2))
                    j2 = min(3, max(0, j2))
                    tmp.append(value_table[i2][j2]/4) # current policy 
                    
                update_table[i][j] = -1 + sum(tmp) #update table with current policy
        value_table = update_table


    print("\n\nRESULT")
    for line in value_table:
        for item in range(4):
                line[item] = round(line[item],1) #round
        print(line)
        


def Value(epoch):
    value_table = np.zeros([grid_height, grid_width], dtype=float) #value table declaration
    for tmp in range(epoch):
        update_table = np.zeros([grid_height, grid_width], dtype=float) ## update table declaration
        for j in range(4): 
            for i in range(4):
                if i==j and (i==0 or i==3):
                    continue

                tmp = []
                
                for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]:
                    i2 = min(3, max(0, i2))
                    for _ in range (2):
                        j2 = min(3, max(0, j2))
                    tmp.append(value_table[i2][j2])

                update_table[i][j] = -1 + max(tmp)
        
        value_table = update_table

    print("\n\nRESULT")
    for line in value_table:
        for item in range(4):
                line[item] = round(line[item],1)
        print(line)

if __name__ == '__main__':
    epoch = 100
    Policy(epoch=epoch)
    Value(epoch=epoch)



RESULT
[  0.  -13.9 -19.9 -21.9]
[-13.9 -17.9 -19.9 -19.9]
[-19.9 -19.9 -17.9 -13.9]
[-21.9 -19.9 -13.9   0. ]


RESULT
[ 0. -1. -2. -3.]
[-1. -2. -3. -2.]
[-2. -3. -2. -1.]
[-3. -2. -1.  0.]


In [22]:
import numpy as np
grid_height =4
grid_width = 4
epoch = 100
policy_table = np.zeros([grid_height, grid_width], dtype=float) ## value table declaration
for tmp in range(epoch):
    for tmp in range(grid_width):
        policy_update_table = np.zeros([grid_height, grid_width], dtype=float) ## update table declaration

    for j in range(grid_width):
        for i in range(grid_height):
            if i==j and (i==0 or i==3):
                continue

            tmp = []

            for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]: # South East North West move pair
                i2 = min(3, max(0, i2))
                j2 = min(3, max(0, j2))
                tmp.append(policy_table[i2][j2]/4) # current policy 
                    
            policy_update_table[i][j] = -1 + sum(tmp) #update table with current policy
    policy_table = policy_update_table


print("\n\nRESULT")
for line in policy_table:
    for item in range(4):
            line[item] = round(line[item],1) #round
    print(line)
    
value_table = np.zeros([grid_height, grid_width], dtype=float) #value table declaration
for tmp in range(epoch):
    value_update_table = np.zeros([grid_height, grid_width], dtype=float) ## update table declaration
    for j in range(4): 
        for i in range(4):
            if i==j and (i==0 or i==3):
                continue

            tmp = []
                
            for i2, j2 in [[i+1,j],[i,j+1],[i-1,j],[i,j-1]]:
                i2 = min(3, max(0, i2))
                for _ in range (2):
                    j2 = min(3, max(0, j2))
                tmp.append(value_table[i2][j2])

            value_update_table[i][j] = -1 + max(tmp)
        
    value_table = value_update_table

print("\n\nRESULT")
for line in value_table:
    for item in range(4):
            line[item] = round(line[item],1)
    print(line)




RESULT
[  0.  -13.9 -19.9 -21.9]
[-13.9 -17.9 -19.9 -19.9]
[-19.9 -19.9 -17.9 -13.9]
[-21.9 -19.9 -13.9   0. ]


RESULT
[ 0. -1. -2. -3.]
[-1. -2. -3. -2.]
[-2. -3. -2. -1.]
[-3. -2. -1.  0.]
